version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
  
  redis:
    container_name: redis_cache
    image: redis:8.2.1
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network

volumes:
  postgres_data:
  redis_data:


networks:
  backend_network:
    driver: bridge